### PR TITLE
Simple cad function

### PR DESCRIPTION
**Pull request by dannab**
Hello
(I'm sorry for the bad english)
I am a craftman,
I found GrblController app perfect for my needs and 
I discovered that it was also written in a very clear way. 
For this reason, being completely ignorant of the java language, 
I tried some modifications that I now use almost every day at work.

I added (thanks to copy and paste) a fragment with basic CAM functions 
but very useful for doing operations without the need for a computer.

With the coordinates that I take directly in jog mode, 
I obtain processes such as facing, pocketing, cutting, contouring on rectangles and circles.

I also added on one of the programmable buttons a function 
to capture the current coordinates point in a file 
that I can use within a CAD program to have references on stock of irregular shapes etc.

I also added inside the window for manually entering the coordinates, 
in the jog fragment ,through a "Neutral" function 
a key that divides the coordinate to be changed by 2, 
very useful for finding the center of a stock 

it's the first time I've tried java, in general on android and Git and 
I imagine there are many mistakes 
but I've been using these new functions for a while without problems 
and I hope they can be useful to other people.
regards

### CODE REVIEW

**Comment by zeevy** [comment]
Thank you very much for your contribution, This is indeed really helpful for lot of people.
I will check and merge this soon

**Comment by zeevy** [comment]
@dannab can you please rebase your fork and resolve the conflicts?

**Comment by dannab** [comment]
Hello
It's my first time using github
I'm not sure what to do...
can you explain it to me?
Regards

Il gio 26 gen 2023, 06:31 zeevy ***@***.***> ha scritto:

**Comment by zeevy** [comment]
@dannab  can you please merge this https://github.com/dannab/grblcontroller/pull/2

**Comment by dannab** [comment]
I did the merge, hope it's ok now

Il ven 27 gen 2023, 08:48 zeevy ***@***.***> ha scritto:

**Pull request merged**
